import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { getuser } from '@/lib/getuser';
import GenielabNavbar from "@/components/GenielabNavbar";
type User = {
  id: string;
  name: string;
  email: string;
};
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SiteGenie ||Profile",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
      const session = await getuser(); // Fetch session data
      const user: User | null = session?.user
      ? {
          id: session.user.id || '', // Ensure id is a string
          name: session.user.name || 'Unknown', // Provide a fallback for name
          email: session.user.email || '', // Ensure email is a string
        }
      : null;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GenielabNavbar user={user} />
        {children}
      </body>
    </html>
  );
}
